# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "tsbox"

  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.network :forwarded_port, guest: 8081, host: 8081  

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
  	puppet.module_path = "~/.puppet/modules"
  end

end
